fruits = ("apple", "mango", "banana", "orange", "coconut", "coconut")
# print(fruits[::3])
# print(len(fruits))
print("apple" in fruits)
# print(dir(fruits))
# print(help(fruits))
print(fruits.index("apple"))
# fruits.add("pineapple")
# fruits.remove("apple")
# fruits.pop()
print(fruits.count("coconut"))
print(fruits)
# for fruit in fruits:
#     print(fruits) 